<<<<<<< HEAD
spring.application.name=persona

server.port=7880
=======
spring.application.name=role-management

server.port=7881
>>>>>>> c2f9c22f66b243da61ea382b80be9ac503b6e649
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_account_manager
spring.datasource.username=user
spring.datasource.password=user
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.connection-init-sql=SET NAMES 'UTF8'
