version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_account_manager
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bd_account_manager
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
